// Copyright (c) 2023 Huawei Device Co., Ltd.
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Asynchronous `Connector` trait and `HttpConnector` implementation.

mod stream;

use core::future::Future;
use std::io::{Error, ErrorKind};
use std::net::SocketAddr;
use std::str::FromStr;
use std::sync::Arc;

#[cfg(target_os = "linux")]
use libc::{gid_t, uid_t};
use ylong_http::request::uri::Uri;
#[cfg(feature = "http3")]
use ylong_runtime::net::{ConnectedUdpSocket, UdpSocket};

use crate::async_impl::dns::{DefaultDnsResolver, EyeBallConfig, HappyEyeballs, Resolver};
use crate::runtime::{AsyncRead, AsyncWrite, TcpStream};
use crate::util::config::{ConnectorConfig, HttpVersion};
/// Information of an IO.
use crate::util::ConnInfo;
use crate::{HttpClientError, Timeout};

/// `Connector` trait used by `async_impl::Client`. `Connector` provides
/// asynchronous connection establishment interfaces.
pub trait Connector {
    /// Streams that this connector produces.
    type Stream: AsyncRead + AsyncWrite + ConnInfo + Unpin + Sync + Send + 'static;

    /// Futures generated by this connector when attempting to create a stream.
    type Future: Future<Output = Result<Self::Stream, HttpClientError>>
        + Unpin
        + Sync
        + Send
        + 'static;

    /// Attempts to establish a connection.
    fn connect(&self, uri: &Uri, http_version: HttpVersion) -> Self::Future;
}

/// Connector for creating HTTP or HTTPS connections asynchronously.
///
/// `HttpConnector` implements `async_impl::Connector` trait.
pub struct HttpConnector {
    config: ConnectorConfig,
    resolver: Arc<dyn Resolver>,
}

impl HttpConnector {
    /// Creates a new `HttpConnector` with a `ConnectorConfig`.
    pub(crate) fn new(config: ConnectorConfig, resolver: Arc<dyn Resolver>) -> Self {
        Self { config, resolver }
    }

    /// Creates a new `HttpConnector` with a given dns `Resolver`.
    pub(crate) fn with_dns_resolver<R>(resolver: R) -> Self
    where
        R: Resolver,
    {
        let resolver = Arc::new(resolver) as Arc<dyn Resolver>;
        Self {
            config: Default::default(),
            resolver,
        }
    }
}

impl Default for HttpConnector {
    fn default() -> Self {
        Self {
            config: Default::default(),
            resolver: Arc::new(DefaultDnsResolver::default()),
        }
    }
}

async fn tcp_stream(eyeballs: HappyEyeballs) -> Result<TcpStream, HttpClientError> {
    eyeballs
        .connect()
        .await
        .map_err(|e| {
            #[cfg(target_os = "linux")]
            if format!("{}", e).contains("failed to lookup address information") {
                return HttpClientError::from_dns_error(crate::ErrorKind::Connect, e);
            }
            #[cfg(target_os = "windows")]
            if let Some(code) = e.raw_os_error() {
                if (0x2329..=0x26B2).contains(&code) || code == 0x2AF9 {
                    return HttpClientError::from_dns_error(crate::ErrorKind::Connect, e);
                }
            }
            HttpClientError::from_io_error(crate::ErrorKind::Connect, e)
        })
        .and_then(|stream| match stream.set_nodelay(true) {
            Ok(()) => Ok(stream),
            Err(e) => err_from_io!(Connect, e),
        })
}

#[cfg(all(target_os = "linux", feature = "ylong_base", feature = "__tls"))]
async fn tcp_stream_with_owner(
    eyeballs: HappyEyeballs,
    uid: uid_t,
    gid: gid_t,
) -> Result<TcpStream, HttpClientError> {
    eyeballs
        .connect_with_owner(uid, gid)
        .await
        .map_err(|e| {
            if format!("{}", e).contains("failed to lookup address information") {
                return HttpClientError::from_dns_error(crate::ErrorKind::Connect, e);
            }
            HttpClientError::from_io_error(crate::ErrorKind::Connect, e)
        })
        .and_then(|stream| match stream.set_nodelay(true) {
            Ok(()) => Ok(stream),
            Err(e) => err_from_io!(Connect, e),
        })
}

async fn dns_query(
    resolver: Arc<dyn Resolver>,
    addr: &str,
) -> Result<Vec<SocketAddr>, HttpClientError> {
    if let Ok(socket_addr) = SocketAddr::from_str(addr) {
        return Ok(vec![socket_addr]);
    }
    let addr_fut = resolver.resolve(addr);
    let socket_addr = addr_fut.await.map_err(|e| {
        HttpClientError::from_dns_error(
            crate::ErrorKind::Connect,
            Error::new(ErrorKind::Interrupted, e),
        )
    })?;
    Ok(socket_addr.collect::<Vec<_>>())
}

async fn eyeballs_connect(
    addrs: Vec<SocketAddr>,
    timeout: Timeout,
) -> Result<TcpStream, HttpClientError> {
    let eyeball_config = EyeBallConfig::new(timeout.inner(), None);
    let happy_eyeballs = HappyEyeballs::new(addrs, eyeball_config);
    tcp_stream(happy_eyeballs).await
}

#[cfg(all(target_os = "linux", feature = "ylong_base", feature = "__tls"))]
async fn eyeballs_connect_with_owner(
    addrs: Vec<SocketAddr>,
    timeout: Timeout,
    uid: uid_t,
    gid: gid_t,
) -> Result<TcpStream, HttpClientError> {
    let eyeball_config = EyeBallConfig::new(timeout.inner(), None);
    let happy_eyeballs = HappyEyeballs::new(addrs, eyeball_config);
    tcp_stream_with_owner(happy_eyeballs, uid, gid).await
}

#[cfg(feature = "http3")]
pub(crate) async fn udp_stream(
    addr: &std::net::SocketAddr,
) -> Result<ConnectedUdpSocket, HttpClientError> {
    let local_addr = match addr {
        std::net::SocketAddr::V4(_) => "0.0.0.0:0",
        std::net::SocketAddr::V6(_) => "[::]:0",
    };
    let sock = UdpSocket::bind(local_addr)
        .await
        .map_err(|e| HttpClientError::from_io_error(crate::ErrorKind::Connect, e))?;
    sock.connect(addr)
        .await
        .map_err(|e| HttpClientError::from_io_error(crate::ErrorKind::Connect, e))
}

#[cfg(not(feature = "__tls"))]
mod no_tls {
    use core::future::Future;
    use core::pin::Pin;
    use std::time::Instant;

    use ylong_http::request::uri::Uri;

    use super::{eyeballs_connect, Connector, HttpConnector};
    use crate::async_impl::connector::dns_query;
    use crate::async_impl::connector::stream::HttpStream;
    use crate::runtime::TcpStream;
    use crate::util::config::HttpVersion;
    use crate::util::interceptor::ConnProtocol;
    use crate::{ConnData, ConnDetail, HttpClientError, TimeGroup};

    impl Connector for HttpConnector {
        type Stream = HttpStream<TcpStream>;
        type Future =
            Pin<Box<dyn Future<Output = Result<Self::Stream, HttpClientError>> + Sync + Send>>;

        fn connect(&self, uri: &Uri, _http_version: HttpVersion) -> Self::Future {
            // Checks if this uri need be proxied.
            let mut is_proxy = false;
            let mut addr = uri.authority().unwrap().to_string();
            if let Some(proxy) = self.config.proxies.match_proxy(uri) {
                addr = proxy.via_proxy(uri).authority().unwrap().to_string();
                is_proxy = true;
            }

            let resolver = self.resolver.clone();
            let timeout = self.config.timeout.clone();
            Box::pin(async move {
                let mut time_group = TimeGroup::default();
                time_group.set_dns_start(Instant::now());
                let socket_addrs = dns_query(resolver, addr.as_str()).await?;
                time_group.set_dns_end(Instant::now());
                time_group.set_tcp_start(Instant::now());
                let stream = eyeballs_connect(socket_addrs, timeout).await?;
                time_group.set_tcp_end(Instant::now());
                let local = stream
                    .local_addr()
                    .map_err(|e| HttpClientError::from_io_error(crate::ErrorKind::Connect, e))?;
                let peer = stream
                    .peer_addr()
                    .map_err(|e| HttpClientError::from_io_error(crate::ErrorKind::Connect, e))?;
                let detail = ConnDetail {
                    protocol: ConnProtocol::Tcp,
                    local,
                    peer,
                    addr,
                };

                let data = ConnData::builder()
                    .time_group(time_group)
                    .proxy(is_proxy)
                    .build(detail);
                Ok(HttpStream::new(stream, data))
            })
        }
    }
}

#[cfg(feature = "__tls")]
mod tls {
    #[cfg(all(target_os = "linux", feature = "ylong_base", feature = "__tls"))]
    use super::eyeballs_connect_with_owner;
    use super::{eyeballs_connect, Connector, HttpConnector};
    use crate::async_impl::connector::dns_query;
    use crate::async_impl::connector::stream::HttpStream;
    use crate::async_impl::mix::MixStream;
    #[cfg(feature = "http3")]
    use crate::async_impl::quic::QuicConn;
    use crate::async_impl::ssl_stream::AsyncSslStream;
    use crate::runtime::TcpStream;
    use crate::util::config::{HttpVersion, ProxyTlsConfig};
    #[cfg(feature = "http2")]
    use crate::util::information::NegotiateInfo;
    use crate::util::interceptor::ConnProtocol;
    use crate::util::proxy_tunnel;
    use crate::{ConnData, ConnDetail, HttpClientError, TimeGroup, TlsConfig};
    use core::future::Future;
    use core::pin::Pin;
    use std::io::{Error, ErrorKind};
    use std::time::Instant;
    use ylong_http::request::uri::{Scheme, Uri};

    #[derive(Clone, Copy, Debug, Eq, PartialEq)]
    enum ProxyRoute {
        DirectHttp,
        DirectHttps,
        HttpOverHttpProxy,
        HttpsOverHttpProxy,
        HttpOverHttpsProxy,
        HttpsOverHttpsProxy,
    }

    impl ProxyRoute {
        fn new(scheme: &Scheme, is_proxy: bool, is_https_proxy: bool) -> Self {
            if *scheme == Scheme::HTTP {
                if !is_proxy {
                    Self::DirectHttp
                } else if is_https_proxy {
                    Self::HttpOverHttpsProxy
                } else {
                    Self::HttpOverHttpProxy
                }
            } else if !is_proxy {
                Self::DirectHttps
            } else if is_https_proxy {
                Self::HttpsOverHttpsProxy
            } else {
                Self::HttpsOverHttpProxy
            }
        }

        fn is_proxy(self) -> bool {
            !matches!(self, Self::DirectHttp | Self::DirectHttps)
        }

        fn is_https_proxy(self) -> bool {
            matches!(self, Self::HttpOverHttpsProxy | Self::HttpsOverHttpsProxy)
        }
    }

    impl Connector for HttpConnector {
        type Stream = HttpStream<MixStream>;
        type Future =
            Pin<Box<dyn Future<Output = Result<Self::Stream, HttpClientError>> + Sync + Send>>;

        fn connect(&self, uri: &Uri, _http_version: HttpVersion) -> Self::Future {
            // Make sure all parts of uri is accurate.
            let mut addr = uri.authority().unwrap().to_string();
            let mut auth = None;
            let mut is_proxy = false;
            let mut proxy_tls_config = None;
            let mut proxy_host = None;

            if let Some(proxy) = self.config.proxies.match_proxy(uri) {
                let proxy_info = proxy.intercept.proxy_info();
                addr = proxy.via_proxy(uri).authority().unwrap().to_string();
                auth = proxy
                    .intercept
                    .proxy_info()
                    .basic_auth
                    .as_ref()
                    .and_then(|v| v.to_string().ok());
                is_proxy = true;
                if proxy.is_https_proxy() {
                    proxy_tls_config = Some(proxy.tls_config.clone());
                    proxy_host = Some(proxy_info.authority().host().as_str().to_string());
                }
            }
            let route =
                ProxyRoute::new(uri.scheme().unwrap(), is_proxy, proxy_tls_config.is_some());
            #[cfg(all(target_os = "linux", feature = "ylong_base", feature = "__tls"))]
            let fchown = self.config.fchown.clone();
            let resolver = self.resolver.clone();
            let timeout = self.config.timeout.clone();
            match route {
                ProxyRoute::DirectHttp
                | ProxyRoute::HttpOverHttpProxy
                | ProxyRoute::HttpOverHttpsProxy => Box::pin(async move {
                    let mut time_group = TimeGroup::default();
                    time_group.set_dns_start(Instant::now());
                    let socket_addrs = dns_query(resolver, addr.as_str()).await?;
                    time_group.set_dns_end(Instant::now());
                    time_group.set_tcp_start(Instant::now());
                    #[cfg(not(all(
                        target_os = "linux",
                        feature = "ylong_base",
                        feature = "__tls"
                    )))]
                    let stream = eyeballs_connect(socket_addrs, timeout).await?;
                    #[cfg(all(target_os = "linux", feature = "ylong_base", feature = "__tls"))]
                    let stream = if let Some(fchown) = fchown {
                        eyeballs_connect_with_owner(socket_addrs, timeout, fchown.uid, fchown.gid)
                            .await?
                    } else {
                        eyeballs_connect(socket_addrs, timeout).await?
                    };

                    time_group.set_tcp_end(Instant::now());

                    let local = stream.local_addr().map_err(|e| {
                        HttpClientError::from_io_error(crate::ErrorKind::Connect, e)
                    })?;
                    let peer = stream.peer_addr().map_err(|e| {
                        HttpClientError::from_io_error(crate::ErrorKind::Connect, e)
                    })?;
                    let detail = ConnDetail {
                        protocol: ConnProtocol::Tcp,
                        local,
                        peer,
                        addr,
                    };
                    let stream = if route.is_https_proxy() {
                        let proxy_tls_config = proxy_tls_config.ok_or_else(|| {
                            HttpClientError::from_str(
                                crate::ErrorKind::Connect,
                                "HTTPS proxy TLS config is missing",
                            )
                        })?;
                        let proxy_host = proxy_host.ok_or_else(|| {
                            HttpClientError::from_str(
                                crate::ErrorKind::Connect,
                                "HTTPS proxy host is missing",
                            )
                        })?;
                        time_group.set_tls_start(Instant::now());
                        let stream =
                            proxy_tls_connect(proxy_tls_config, &proxy_host, stream).await?;
                        time_group.set_tls_end(Instant::now());
                        MixStream::Https(stream)
                    } else {
                        MixStream::Http(stream)
                    };

                    let data = ConnData::builder()
                        .time_group(time_group)
                        .proxy(route.is_proxy())
                        .build(detail);

                    Ok(HttpStream::new(stream, data))
                }),
                ProxyRoute::DirectHttps
                | ProxyRoute::HttpsOverHttpProxy
                | ProxyRoute::HttpsOverHttpsProxy => {
                    let host = uri.host().unwrap().to_string();
                    let port = uri.port().unwrap().as_u16().unwrap();
                    let config = self.config.tls.clone();
                    #[cfg(feature = "http3")]
                    if _http_version == HttpVersion::Http3 {
                        return Box::pin(async move {
                            let mut time_group = TimeGroup::default();
                            time_group.set_dns_start(Instant::now());
                            let addr_fut = resolver.resolve(&addr);
                            let addrs = addr_fut.await.map_err(|e| {
                                HttpClientError::from_dns_error(
                                    crate::ErrorKind::Connect,
                                    Error::new(ErrorKind::Interrupted, e),
                                )
                            })?;
                            time_group.set_dns_end(Instant::now());
                            time_group.set_quic_start(Instant::now());
                            let mut last_e = None;
                            for addr_it in addrs {
                                let udp_socket = match super::udp_stream(&addr_it).await {
                                    Ok(socket) => socket,
                                    Err(e) => {
                                        last_e = Some(e);
                                        continue;
                                    }
                                };
                                let local = udp_socket.local_addr().map_err(|e| {
                                    HttpClientError::from_io_error(crate::ErrorKind::Connect, e)
                                })?;
                                let peer = udp_socket.peer_addr().map_err(|e| {
                                    HttpClientError::from_io_error(crate::ErrorKind::Connect, e)
                                })?;
                                let detail = ConnDetail {
                                    protocol: ConnProtocol::Quic,
                                    local,
                                    peer,
                                    addr: addr.clone(),
                                };

                                let mut data = ConnData::builder()
                                    .time_group(time_group.clone())
                                    .proxy(route.is_proxy())
                                    .build(detail);

                                let mut stream =
                                    HttpStream::new(MixStream::Udp(udp_socket), data.clone());
                                let Ok(quic_conn) =
                                    QuicConn::connect(&mut stream, &config, &host).await
                                else {
                                    continue;
                                };
                                stream.set_quic_conn(quic_conn);
                                data.time_group_mut().set_quic_end(Instant::now());
                                stream.set_conn_data(data);
                                return Ok(stream);
                            }

                            Err(last_e.unwrap_or(HttpClientError::from_str(
                                crate::ErrorKind::Connect,
                                "connect failed",
                            )))
                        });
                    }
                    Box::pin(async move {
                        let mut time_group = TimeGroup::default();
                        time_group.set_dns_start(Instant::now());
                        let socket_addrs = dns_query(resolver, addr.as_str()).await?;
                        time_group.set_dns_end(Instant::now());
                        time_group.set_tcp_start(Instant::now());
                        #[cfg(not(all(
                            target_os = "linux",
                            feature = "ylong_base",
                            feature = "__tls"
                        )))]
                        let stream = eyeballs_connect(socket_addrs, timeout).await?;
                        #[cfg(all(target_os = "linux", feature = "ylong_base", feature = "__tls",))]
                        let stream = if let Some(fchown) = fchown {
                            eyeballs_connect_with_owner(
                                socket_addrs,
                                timeout,
                                fchown.uid,
                                fchown.gid,
                            )
                            .await?
                        } else {
                            eyeballs_connect(socket_addrs, timeout).await?
                        };

                        time_group.set_tcp_end(Instant::now());

                        https_connect(
                            config,
                            addr,
                            stream,
                            route,
                            (auth, host, port),
                            proxy_tls_config,
                            proxy_host,
                            time_group,
                        )
                        .await
                    })
                }
            }
        }
    }

    async fn https_connect(
        config: TlsConfig,
        addr: String,
        tcp_stream: TcpStream,
        route: ProxyRoute,
        (auth, host, port): (Option<String>, String, u16),
        proxy_tls_config: Option<ProxyTlsConfig>,
        proxy_host: Option<String>,
        mut time_group: TimeGroup,
    ) -> Result<HttpStream<MixStream>, HttpClientError> {
        let tcp = tcp_stream;
        let local = tcp
            .local_addr()
            .map_err(|e| HttpClientError::from_io_error(crate::ErrorKind::Connect, e))?;
        let peer = tcp
            .peer_addr()
            .map_err(|e| HttpClientError::from_io_error(crate::ErrorKind::Connect, e))?;

        let origin_authority = format!("{host}:{port}");

        match route {
            ProxyRoute::HttpsOverHttpsProxy => {
                let proxy_tls_config = proxy_tls_config.ok_or_else(|| {
                    HttpClientError::from_str(
                        crate::ErrorKind::Connect,
                        "HTTPS proxy TLS config is missing",
                    )
                })?;
                let proxy_host = proxy_host.ok_or_else(|| {
                    HttpClientError::from_str(
                        crate::ErrorKind::Connect,
                        "HTTPS proxy host is missing",
                    )
                })?;
                time_group.set_tls_start(Instant::now());
                let proxy_stream = proxy_tls_connect(proxy_tls_config, &proxy_host, tcp).await?;
                let proxy_stream = proxy_tunnel::connect(proxy_stream, &host, port, auth)
                    .await
                    .map_err(|e| HttpClientError::from_io_error(crate::ErrorKind::Connect, e))?;
                let pinned_key = config.pinning_host_match(origin_authority.as_str());
                let mut stream = config
                    .ssl_new(&host)
                    .and_then(|ssl| AsyncSslStream::new(ssl.into_inner(), proxy_stream, pinned_key))
                    .map_err(|e| {
                        HttpClientError::from_tls_error(
                            crate::ErrorKind::Connect,
                            Error::new(ErrorKind::Other, e),
                        )
                    })?;
                Pin::new(&mut stream).connect().await.map_err(|e| {
                    HttpClientError::from_tls_error(
                        crate::ErrorKind::Connect,
                        Error::new(ErrorKind::Other, e),
                    )
                })?;
                time_group.set_tls_end(Instant::now());

                #[cfg(feature = "http2")]
                let alpn = stream.negotiated_alpn_protocol().map(Vec::from);
                let detail = ConnDetail {
                    protocol: ConnProtocol::Tcp,
                    local,
                    peer,
                    addr,
                };

                #[cfg(feature = "http2")]
                let data = ConnData::builder()
                    .time_group(time_group)
                    .proxy(route.is_proxy())
                    .negotiate(NegotiateInfo::from_alpn(alpn))
                    .build(detail);

                #[cfg(not(feature = "http2"))]
                let data = ConnData::builder()
                    .time_group(time_group)
                    .proxy(route.is_proxy())
                    .build(detail);

                return Ok(HttpStream::new(MixStream::HttpsProxy(stream), data));
            }
            ProxyRoute::HttpsOverHttpProxy => {
                let tcp = proxy_tunnel::connect(tcp, &host, port, auth)
                    .await
                    .map_err(|e| HttpClientError::from_io_error(crate::ErrorKind::Connect, e))?;
                let pinned_key = config.pinning_host_match(origin_authority.as_str());
                let mut stream = config
                    .ssl_new(&host)
                    .and_then(|ssl| AsyncSslStream::new(ssl.into_inner(), tcp, pinned_key))
                    .map_err(|e| {
                        HttpClientError::from_tls_error(
                            crate::ErrorKind::Connect,
                            Error::new(ErrorKind::Other, e),
                        )
                    })?;

                time_group.set_tls_start(Instant::now());
                Pin::new(&mut stream).connect().await.map_err(|e| {
                    HttpClientError::from_tls_error(
                        crate::ErrorKind::Connect,
                        Error::new(ErrorKind::Other, e),
                    )
                })?;
                time_group.set_tls_end(Instant::now());

                #[cfg(feature = "http2")]
                let alpn = stream.negotiated_alpn_protocol().map(Vec::from);
                let detail = ConnDetail {
                    protocol: ConnProtocol::Tcp,
                    local,
                    peer,
                    addr,
                };

                #[cfg(feature = "http2")]
                let data = ConnData::builder()
                    .time_group(time_group)
                    .proxy(route.is_proxy())
                    .negotiate(NegotiateInfo::from_alpn(alpn))
                    .build(detail);

                #[cfg(not(feature = "http2"))]
                let data = ConnData::builder()
                    .time_group(time_group)
                    .proxy(route.is_proxy())
                    .build(detail);

                return Ok(HttpStream::new(MixStream::Https(stream), data));
            }
            ProxyRoute::DirectHttps => {}
            _ => {
                return Err(HttpClientError::from_str(
                    crate::ErrorKind::Connect,
                    "invalid proxy route for HTTPS target",
                ));
            }
        }

        let pinned_key = config.pinning_host_match(origin_authority.as_str());
        let mut stream = config
            .ssl_new(&host)
            .and_then(|ssl| AsyncSslStream::new(ssl.into_inner(), tcp, pinned_key))
            .map_err(|e| {
                HttpClientError::from_tls_error(
                    crate::ErrorKind::Connect,
                    Error::new(ErrorKind::Other, e),
                )
            })?;

        time_group.set_tls_start(Instant::now());
        Pin::new(&mut stream).connect().await.map_err(|e| {
            HttpClientError::from_tls_error(
                crate::ErrorKind::Connect,
                Error::new(ErrorKind::Other, e),
            )
        })?;
        time_group.set_tls_end(Instant::now());

        #[cfg(feature = "http2")]
        let alpn = stream.negotiated_alpn_protocol().map(Vec::from);
        let detail = ConnDetail {
            protocol: ConnProtocol::Tcp,
            local,
            peer,
            addr,
        };

        #[cfg(feature = "http2")]
        let data = ConnData::builder()
            .time_group(time_group)
            .proxy(route.is_proxy())
            .negotiate(NegotiateInfo::from_alpn(alpn))
            .build(detail);

        #[cfg(not(feature = "http2"))]
        let data = ConnData::builder()
            .time_group(time_group)
            .proxy(route.is_proxy())
            .build(detail);

        Ok(HttpStream::new(MixStream::Https(stream), data))
    }

    async fn proxy_tls_connect(
        proxy_config: ProxyTlsConfig,
        proxy_host: &str,
        tcp: TcpStream,
    ) -> Result<AsyncSslStream<TcpStream>, HttpClientError> {
        let proxy_config = proxy_config.build()?;
        let mut stream = proxy_config
            .ssl_new(proxy_host)
            .and_then(|ssl| AsyncSslStream::new(ssl.into_inner(), tcp, None))
            .map_err(|e| {
                HttpClientError::from_tls_error(
                    crate::ErrorKind::Connect,
                    Error::new(ErrorKind::Other, e),
                )
            })?;

        Pin::new(&mut stream).connect().await.map_err(|e| {
            HttpClientError::from_tls_error(
                crate::ErrorKind::Connect,
                Error::new(ErrorKind::Other, e),
            )
        })?;

        Ok(stream)
    }
}
